---
abstract: ~
author:
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mason-Plugin-ClassAttribute
no_index:
  directory:
    - inc
requires:
  Mason: 2.13
  MooseX::ClassAttribute: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: undef
