---
abstract: ~
author:
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mason-Plugin-ClassAttribute
no_index:
  directory:
    - inc
    - t
requires:
  Mason: 2.13
  MooseX::ClassAttribute: 0
resources:
  homepage: https://github.com/bokutin/Mason-Plugin-ClassAttribute/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/bokutin/Mason-Plugin-ClassAttribute.git
    web: https://github.com/bokutin/Mason-Plugin-ClassAttribute/tree
version: undef
